_target_: src.models.model.SRModel

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.sr_model.create_model
  model: "EDSR"
  weight_path: ${paths.weight_dir}  # model.py
  upscale: 4

# compile model for faster training with pytorch 2.0
compile: false

# num_classes: 1000