_target_: src.models.model.SegmentationModel

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.001
  momentum: 0.9

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.instance-segmentation_model.create_model
  model: mask_rcnn

# compile model for faster training with pytorch 2.0
compile: false

num_classes: 91