defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_{val/acc:.4f}"
  monitor: "val/psnr"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

# model_checkpoint_ssim:
#   _target_: lightning.pytorch.callbacks.ModelCheckpoint
#   dirpath: ${paths.output_dir}/checkpoints
#   filename: "epoch_{epoch:03d}_{val/acc:.4f}"
#   monitor: "val/ssim"
#   mode: "max"
#   save_last: True
#   auto_insert_metric_name: False

early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: "val/psnr"
  patience: 100
  mode: "max"

# early_stopping_ssim:
#   _target_: lightning.pytorch.callbacks.EarlyStopping
#   monitor: "val/ssim"
#   patience: 100
#   mode: "max"

model_summary:
  max_depth: -1
