# @package _global_

defaults:
  - _self_
  - data: predict
  - model: pascal
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

task_name: "predict"

tags: ["dev"]

ckpt_path: null
pred_image: null
